# Use an official Python runtime as a parent image
FROM python:3.11-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container at /app
COPY requirements.txt .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of your application's code into the container at /app
COPY . .

# Expose the port the app runs on. Hugging Face Spaces uses 7860.
EXPOSE 7860

# Define the command to run your app using Gunicorn
CMD ["gunicorn", "--bind", "0.0.0.0:7860", "--workers=1", "run:create_app()"]